version: '3.4'

services:
  mssql:
    image: mcmoe/mssqldocker:latest
    ports:
      - 21433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_DB: test_db
      MSSQL_USER: test
      SA_PASSWORD: Secret123
      MSSQL_PASSWORD: Secret123

  mysql-1:
    image: mysql:8
    ports:
      - 23306:3306
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: Secret123
      MYSQL_ROOT_PASSWORD: Secret123

  pg:
    image: postgres:alpine
    ports:
      - 25432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: Secret123
      POSTGRES_DB: test_db

  mysql-2:
    image: mysql:8
    ports:
      - 23307:3306
    command: |
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: Secret123
      MYSQL_ROOT_PASSWORD: Secret123

  ssh-server:
    image: linuxserver/openssh-server
    ports:
      - 2222:2222
    environment:
      # Allow port forwarding. See:
      # https://github.com/linuxserver/docker-mods/tree/openssh-server-ssh-tunnel
      DOCKER_MODS: linuxserver/mods:openssh-server-ssh-tunnel
      PASSWORD_ACCESS: "true"
      USER_NAME: user
      USER_PASSWORD: pass

  wait-all:
    image: jwilder/dockerize
    command: |
      -wait tcp://mssql:1433
      -wait tcp://mysql-1:3306
      -wait tcp://pg:5432
      -wait tcp://mysql-2:3306
      -wait tcp://ssh-server:2222
      -timeout 30s
